//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharpExtensions.Analyzers.Test.InitOnlyOptional {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InitOnlyOptionalTestCases {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InitOnlyOptionalTestCases() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSharpExtensions.Analyzers.Test.InitOnlyOptional.InitOnlyOptionalTestCases", typeof(InitOnlyOptionalTestCases).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using SmartAnalyzers.CSharpExtensions.Annotations;
        ///
        ///namespace CSharpExtensions.Analyzers.Test.RequiredPropertiesInitialization.TestCaseData
        ///{
        ///    public class UserDTO
        ///    {
        ///        public string FirstName { get; set; }
        ///        public string LastName { get; set; }
        ///        [InitOnlyOptional]
        ///        [|public int Age { get; set; }|]
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string _001_ReportMissingPropertyInitialization {
            get {
                return ResourceManager.GetString("_001_ReportMissingPropertyInitialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using SmartAnalyzers.CSharpExtensions.Annotations;
        ///
        ///namespace CSharpExtensions.Analyzers.Test.RequiredPropertiesInitialization.TestCaseData
        ///{
        ///    public class UserDTO
        ///    {
        ///        public string FirstName { get; set; }
        ///        public string LastName { get; set; }
        ///        [InitOnlyOptional]
        ///        [|public int Age; |]
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string _002_ReportMissingFieldInitialization {
            get {
                return ResourceManager.GetString("_002_ReportMissingFieldInitialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using SmartAnalyzers.CSharpExtensions.Annotations;
        ///
        ///namespace CSharpExtensions.Analyzers.Test.RequiredPropertiesInitialization.TestCaseData
        ///{
        ///    public class UserDTO
        ///    {
        ///        public string FirstName { get; set; }
        ///        public string LastName { get; set; }
        ///        [InitOnlyOptional]
        ///        [|public int Age { get; set; }|]
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string _003_DoNotReportMissingPropertyInitialization {
            get {
                return ResourceManager.GetString("_003_DoNotReportMissingPropertyInitialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using SmartAnalyzers.CSharpExtensions.Annotations;
        ///
        ///namespace CSharpExtensions.Analyzers.Test.RequiredPropertiesInitialization.TestCaseData
        ///{
        ///    public class UserDTO
        ///    {
        ///        public string FirstName { get; set; }
        ///        public string LastName { get; set; }
        ///        [InitOnlyOptional]
        ///        [|public int Age; |]
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string _004_DoNotReportMissingFieldInitialization {
            get {
                return ResourceManager.GetString("_004_DoNotReportMissingFieldInitialization", resourceCulture);
            }
        }
    }
}
