//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharpExtensions.Analyzers.Test.ReturnValueUnused {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ReturnValueUnusedTestsTestCases {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReturnValueUnusedTestsTestCases() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSharpExtensions.Analyzers.Test.ReturnValueUnused.ReturnValueUnusedTestsTestCases" +
                            "", typeof(ReturnValueUnusedTestsTestCases).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace TestNamespace
        ///{
        ///    class SampleClass
        ///    {
        ///        public void Test()
        ///        {
        ///            [|DoSomething()|];
        ///        }
        ///
        ///        public int DoSomething() =&gt; 1;
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string _001_UnusedReturnValueOfPureMethod {
            get {
                return ResourceManager.GetString("_001_UnusedReturnValueOfPureMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace TestNamespace
        ///{
        ///    class SampleClass
        ///    {
        ///        public void Test()
        ///        {
        ///            [|DoSomething()|];
        ///        }
        ///
        ///        public void DoSomething() =&gt; throw null;
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string _002_VoidReturnMethod {
            get {
                return ResourceManager.GetString("_002_VoidReturnMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Threading.Tasks;
        ///
        ///namespace TestNamespace
        ///{
        ///    class SampleClass
        ///    {
        ///        public async Task Test()
        ///        {
        ///            [|await DoSomething()|];
        ///        }
        ///
        ///        public Task&lt;int&gt; DoSomething() =&gt; Task.FromResult(1);
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string _003_AwaitExpression {
            get {
                return ResourceManager.GetString("_003_AwaitExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Threading.Tasks;
        ///
        ///namespace TestNamespace
        ///{
        ///    class SampleClass
        ///    {
        ///        public async Task Test()
        ///        {
        ///            [|await DoSomething()|];
        ///        }
        ///
        ///       public Task DoSomething() =&gt; Task.CompletedTask;
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string _004_AwaitTaskNoValueExpression {
            get {
                return ResourceManager.GetString("_004_AwaitTaskNoValueExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace TestNamespace
        ///{
        ///    class SampleClass
        ///    {
        ///        public void Test()
        ///        {
        ///            [|new OtherType()|];
        ///        }
        ///    }
        ///
        ///    class OtherType
        ///    {
        ///        
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string _005_NewObjectExpression {
            get {
                return ResourceManager.GetString("_005_NewObjectExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace TestNamespace
        ///{
        ///    class SampleClass
        ///    {
        ///        public void Test()
        ///        {
        ///            var x = [|DoSomething()|];
        ///        }
        ///
        ///        public int DoSomething() =&gt; 1;
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string _006_UsedReturnValueOfPureMethod {
            get {
                return ResourceManager.GetString("_006_UsedReturnValueOfPureMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Threading.Tasks;
        ///
        ///namespace TestNamespace
        ///{
        ///    class SampleClass
        ///    {
        ///        public async Task Test()
        ///        {
        ///            var x = [|await DoSomething()|];
        ///        }
        ///
        ///        public Task&lt;int&gt; DoSomething() =&gt; Task.FromResult(1);
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string _007_UsedValueFromAwaitExpression {
            get {
                return ResourceManager.GetString("_007_UsedValueFromAwaitExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace TestNamespace
        ///{
        ///    class SampleClass
        ///    {
        ///        public void Test()
        ///        {
        ///            if([|IsOk()|])
        ///            {
        ///            }
        ///        }
        ///
        ///        public bool IsOk() =&gt; true;
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string _008_UsedReturnValueOfPureMethodByIfClause {
            get {
                return ResourceManager.GetString("_008_UsedReturnValueOfPureMethodByIfClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace TestNamespace
        ///{
        ///    class SampleClass
        ///    {
        ///        public void Test()
        ///        {
        ///            ShouldDo([|IsOk()|]);
        ///        }
        ///
        ///        public void ShouldDo(bool ok) =&gt; throw null;
        ///
        ///        public bool IsOk() =&gt; true;
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string _009_UsedReturnValueOfPureMethodByOtherExpression {
            get {
                return ResourceManager.GetString("_009_UsedReturnValueOfPureMethodByOtherExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace TestNamespace
        ///{
        ///    class SampleClass
        ///    {
        ///        public bool IsBetter()
        ///        {
        ///            return [|IsOk()|];
        ///        }
        ///
        ///        public bool IsOk() =&gt; true;
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string _010_UsedReturnValueOfPureMethodByReturn {
            get {
                return ResourceManager.GetString("_010_UsedReturnValueOfPureMethodByReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace TestNamespace
        ///{
        ///    class SampleClass
        ///    {
        ///        public bool IsBetter() =&gt; [|IsOk()|];
        ///
        ///        public bool IsOk() =&gt; true;
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string _011_UsedReturnValueOfPureMethodByArrowExpression {
            get {
                return ResourceManager.GetString("_011_UsedReturnValueOfPureMethodByArrowExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace TestNamespace
        ///{
        ///    class SampleClass
        ///    {
        ///        public void Do()
        ///        {
        ///            [|this.Other.IsOk()|];
        ///        }
        ///
        ///       public OtherType Other = new OtherType();
        ///    }
        ///
        ///    class OtherType
        ///    {
        ///        public bool IsOk() =&gt; true;
        ///    }
        ///}.
        /// </summary>
        internal static string _012_UnusedValueFromComplexExpression {
            get {
                return ResourceManager.GetString("_012_UnusedValueFromComplexExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///namespace TestNamespace
        ///{
        ///    class SampleClass
        ///    {
        ///        public void Test()
        ///        {
        ///            [|DoSomething()|];
        ///        }
        ///
        ///        public IDisposable DoSomething() =&gt; throw new NotImplementedException();
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string _013_UnusedDirectDisposable {
            get {
                return ResourceManager.GetString("_013_UnusedDirectDisposable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///namespace TestNamespace
        ///{
        ///    class SampleClass
        ///    {
        ///        public void Test()
        ///        {
        ///            [|DoSomething()|];
        ///        }
        ///
        ///        public MyResource DoSomething() =&gt; throw new NotImplementedException();
        ///    }
        ///
        ///    class MyResource: IDisposable
        ///    {
        ///        public void Dispose()  =&gt; throw new NotImplementedException();
        ///    }
        ///}.
        /// </summary>
        internal static string _014_UnusedInheritedDisposable {
            get {
                return ResourceManager.GetString("_014_UnusedInheritedDisposable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///namespace TestNamespace
        ///{
        ///    class SampleClass
        ///    {
        ///        public void Test()
        ///        {
        ///            [|DoSomething()|];
        ///        }
        ///
        ///        public MyResource DoSomething() =&gt; throw new NotImplementedException();
        ///    }
        ///
        ///    interface IMyResource :IDisposable {}
        ///
        ///    class MyResource: IMyResource
        ///    {
        ///        public void Dispose()  =&gt; throw new NotImplementedException();
        ///    }
        ///}.
        /// </summary>
        internal static string _015_UnusedInheritedInterfaceDisposable {
            get {
                return ResourceManager.GetString("_015_UnusedInheritedInterfaceDisposable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///namespace TestNamespace
        ///{
        ///    class SampleClass
        ///    {
        ///        public void Test()
        ///        {
        ///            [|DoSomething()|];
        ///        }
        ///
        ///        public IMyResource DoSomething() =&gt; throw new NotImplementedException();
        ///    }
        ///
        ///    interface IMyResource :IDisposable {}
        ///
        ///    class MyResource: IMyResource
        ///    {
        ///        public void Dispose()  =&gt; throw new NotImplementedException();
        ///    }
        ///}.
        /// </summary>
        internal static string _016_UnusedInheritedInterfaceWhenReturningInterfaceDisposable {
            get {
                return ResourceManager.GetString("_016_UnusedInheritedInterfaceWhenReturningInterfaceDisposable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Threading.Tasks;
        ///
        ///namespace TestNamespace
        ///{
        ///    class SampleClass
        ///    {
        ///        public async Task Test()
        ///        {
        ///            await [|DoSomething()|];
        ///        }
        ///
        ///        public Task&lt;IMyResource&gt; DoSomething() =&gt; throw new NotImplementedException();
        ///    }
        ///
        ///    interface IMyResource :IDisposable {}
        ///
        ///    class MyResource: IMyResource
        ///    {
        ///        public void Dispose()  =&gt; throw new NotImplementedException();
        ///    }
        ///}.
        /// </summary>
        internal static string _017_UnusedInheritedInterfaceDisposableAwait {
            get {
                return ResourceManager.GetString("_017_UnusedInheritedInterfaceDisposableAwait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Threading.Tasks;
        ///
        ///namespace TestNamespace
        ///{
        ///    class SampleClass
        ///    {
        ///        public async Task Test()
        ///        {
        ///            [|Task.Delay(10)|];
        ///        }
        ///    }
        ///}.
        /// </summary>
        internal static string _018_UnusedAsyncResult {
            get {
                return ResourceManager.GetString("_018_UnusedAsyncResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Threading.Tasks;
        ///
        ///namespace TestNamespace
        ///{
        ///    class SampleClass
        ///    {
        ///        public async Task Test()
        ///        {
        ///            await [|Task.Delay(10)|];
        ///        }
        ///    }
        ///}.
        /// </summary>
        internal static string _019_AwaitedAsyncResult {
            get {
                return ResourceManager.GetString("_019_AwaitedAsyncResult", resourceCulture);
            }
        }
    }
}
