//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharpExtensions.Analyzers.Test.ReadonlyTypeFieldsSet {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ReadonlyTypeFieldsSetTestCases {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReadonlyTypeFieldsSetTestCases() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSharpExtensions.Analyzers.Test.ReadonlyTypeFieldsSet.ReadonlyTypeFieldsSetTestCa" +
                            "ses", typeof(ReadonlyTypeFieldsSetTestCases).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using SmartAnalyzers.CSharpExtensions.Annotations;
        ///
        ///namespace CSharpExtensions.Analyzers.Test.RequiredPropertiesInitialization.TestCaseData
        ///{
        ///    class Test
        ///    {
        ///        public void DoSomething()
        ///        {
        ///            var user = new UserDTO()
        ///            {
        ///                FirstName = &quot;John&quot;,
        ///                LastName = &quot;Doe&quot;,
        ///                Age = 20
        ///            };
        ///        }
        ///    }
        ///
        ///    [InitOnly]
        ///    public class UserDTO [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _001_DoNotReportModificationInInitBlock {
            get {
                return ResourceManager.GetString("_001_DoNotReportModificationInInitBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using SmartAnalyzers.CSharpExtensions.Annotations;
        ///
        ///namespace CSharpExtensions.Analyzers.Test.RequiredPropertiesInitialization.TestCaseData
        ///{
        ///    class Test
        ///    {
        ///        public void DoSomething()
        ///        {
        ///            var user = new UserDTO()
        ///            {
        ///                FirstName = &quot;John&quot;,
        ///                LastName = &quot;Doe&quot;,
        ///                Age = 20
        ///            };
        ///            [|user.Age = 25|];
        ///        }
        ///    }
        ///
        ///    [Ini [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _002_ReportModificationOutsideInitBlock {
            get {
                return ResourceManager.GetString("_002_ReportModificationOutsideInitBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using SmartAnalyzers.CSharpExtensions.Annotations;
        ///
        ///namespace CSharpExtensions.Analyzers.Test.RequiredPropertiesInitialization.TestCaseData
        ///{
        ///    [InitOnly]
        ///    public class UserDTO
        ///    {
        ///        public string FirstName { get; set; }
        ///        public string LastName { get; set; }
        ///        public int Age { get; set; }
        ///
        ///        public void SetAge(int newAge)
        ///        {
        ///            [|this.Age = newAge|];
        ///        }
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string _003_ReportModificationInOwnMethodViaThis {
            get {
                return ResourceManager.GetString("_003_ReportModificationInOwnMethodViaThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using SmartAnalyzers.CSharpExtensions.Annotations;
        ///
        ///namespace CSharpExtensions.Analyzers.Test.RequiredPropertiesInitialization.TestCaseData
        ///{
        ///    [InitOnly]
        ///    public class UserDTO
        ///    {
        ///        public string FirstName { get; set; }
        ///        public string LastName { get; set; }
        ///        public int Age { get; set; }
        ///
        ///        public void SetAge(int newAge)
        ///        {
        ///            [|Age = newAge|];
        ///        }
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string _004_ReportModificationInOwnMethodWithoutThis {
            get {
                return ResourceManager.GetString("_004_ReportModificationInOwnMethodWithoutThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using SmartAnalyzers.CSharpExtensions.Annotations;
        ///
        ///namespace CSharpExtensions.Analyzers.Test.RequiredPropertiesInitialization.TestCaseData
        ///{
        ///    [InitOnly]
        ///    public class UserDTO
        ///    {
        ///        public string FirstName { get; set; }
        ///        public string LastName { get; set; }
        ///        public int Age { get; set; }
        ///
        ///        public UserDTO(string firstName)
        ///        {
        ///            FirstName = firstName;
        ///        }
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string _005_DoNotReportModificationInOwnConstructor {
            get {
                return ResourceManager.GetString("_005_DoNotReportModificationInOwnConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using SmartAnalyzers.CSharpExtensions.Annotations;
        ///
        ///namespace CSharpExtensions.Analyzers.Test.RequiredPropertiesInitialization.TestCaseData
        ///{
        ///    class Test
        ///    {
        ///        public void DoSomething()
        ///        {
        ///            var user = new UserDTO()
        ///            {
        ///                FirstName = &quot;John&quot;,
        ///                LastName = &quot;Doe&quot;,
        ///                Age = 20
        ///            };
        ///            user.FirstName = &quot;aaaaa&quot;;
        ///            [|user.Ag [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _006_ReportModificationOutsideInitBlockForProperty {
            get {
                return ResourceManager.GetString("_006_ReportModificationOutsideInitBlockForProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using SmartAnalyzers.CSharpExtensions.Annotations;
        ///
        ///namespace CSharpExtensions.Analyzers.Test.RequiredPropertiesInitialization.TestCaseData
        ///{
        ///    class Test
        ///    {
        ///        public void DoSomething()
        ///        {
        ///            var user = new UserDTO()
        ///            {
        ///                FirstName = &quot;John&quot;,
        ///                LastName = &quot;Doe&quot;,
        ///                Age = 20
        ///            };
        ///            user.FirstName = &quot;aaaaa&quot;;
        ///        }
        ///    }
        ///
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _007_DoNotReportModificationOutsideInitBlockForNonInitOnly {
            get {
                return ResourceManager.GetString("_007_DoNotReportModificationOutsideInitBlockForNonInitOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using SmartAnalyzers.CSharpExtensions.Annotations;
        ///
        ///namespace CSharpExtensions.Analyzers.Test.RequiredPropertiesInitialization.TestCaseData
        ///{
        ///    class Test
        ///    {
        ///        public void DoSomething()
        ///        {
        ///            var user = new UserDTO()
        ///            {
        ///                FirstName = &quot;John&quot;,
        ///                LastName = &quot;Doe&quot;,
        ///                Age = 20
        ///            };
        ///            [|user.Age = 25|];
        ///        }
        ///    }
        ///
        ///    publ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _008_ReportModificationForInitOnlyOptional {
            get {
                return ResourceManager.GetString("_008_ReportModificationForInitOnlyOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using SmartAnalyzers.CSharpExtensions.Annotations;
        ///
        ///namespace CSharpExtensions.Analyzers.Test.RequiredPropertiesInitialization.TestCaseData
        ///{
        ///    public class UserDTO
        ///    {
        ///        public string FirstName { get; set; }
        ///        public string LastName { get; set; }
        ///        [InitOnlyOptional]
        ///        public int Age { get; set; } = 25;
        ///        
        ///        [InitOnlyOptional]
        ///        public int NewAge  = 25;
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string _009_DoNotReportInitOnlyOptionalModifucationInFieldDefinition {
            get {
                return ResourceManager.GetString("_009_DoNotReportInitOnlyOptionalModifucationInFieldDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using SmartAnalyzers.CSharpExtensions.Annotations;
        ///
        ///namespace CSharpExtensions.Analyzers.Test.RequiredPropertiesInitialization.TestCaseData
        ///{
        ///    [InitOnly]
        ///    public class TestObject
        ///    {
        ///        private string name;
        ///
        ///        public string Name
        ///        {
        ///            get =&gt; name;
        ///            set =&gt; name = $&quot;{MyConst.PREFIX}_{value}&quot;;
        ///        }
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string _010_DoNotReportModificationInOwnProperty {
            get {
                return ResourceManager.GetString("_010_DoNotReportModificationInOwnProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using SmartAnalyzers.CSharpExtensions.Annotations;
        ///
        ///namespace CSharpExtensions.Analyzers.Test.RequiredPropertiesInitialization.TestCaseData
        ///{
        ///    public abstract class BaseClass
        ///    {
        ///        [InitOnly]
        ///        public string MyMember { get; set; }
        ///
        ///        public BaseClass()
        ///        {
        ///           MyMember = &quot;test&quot;; //Allowed
        ///        }
        ///    }
        ///
        ///    public class InheritFromBaseClass : BaseClass
        ///    {
        ///        public InheritFrom [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _011_DoNotReportModificationInInheritedConstructor {
            get {
                return ResourceManager.GetString("_011_DoNotReportModificationInInheritedConstructor", resourceCulture);
            }
        }
    }
}
