//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharpExtensions.Analyzers.Test.TwinTypes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TwinTypeAnalyzerTestsTestCases {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TwinTypeAnalyzerTestsTestCases() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSharpExtensions.Analyzers.Test.TwinTypes.TwinTypeAnalyzerTestsTestCases", typeof(TwinTypeAnalyzerTestsTestCases).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using SmartAnalyzers.CSharpExtensions.Annotations;
        ///
        ///namespace CSharpExtensions.Analyzers.Test.RequiredPropertiesInitialization.TestCaseData
        ///{
        ///
        ///    [TwinType(typeof(UserEntity))]
        ///    public class [|UserDTO|]
        ///    {
        ///        public string FirstName { get; set; }
        ///        public string LastName { get; set; }        
        ///    }
        ///    
        ///    public class UserEntity
        ///    {
        ///        public string FirstName { get; set; }
        ///        public string La [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _001_MissingProperties {
            get {
                return ResourceManager.GetString("_001_MissingProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using SmartAnalyzers.CSharpExtensions.Annotations;
        ///
        ///namespace CSharpExtensions.Analyzers.Test.RequiredPropertiesInitialization.TestCaseData
        ///{
        ///
        ///    [TwinType(typeof(UserEntity))]
        ///    public class [|UserDTO|]
        ///    {
        ///        public string FirstName { get; set; }
        ///        public string LastName { get; set; }        
        ///    }
        ///    
        ///    public class UserEntity
        ///    {
        ///        public string FirstName { get; set; }
        ///        public string La [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _002_MissingFields {
            get {
                return ResourceManager.GetString("_002_MissingFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using SmartAnalyzers.CSharpExtensions.Annotations;
        ///
        ///namespace CSharpExtensions.Analyzers.Test.RequiredPropertiesInitialization.TestCaseData
        ///{
        ///
        ///    [TwinType(typeof(UserEntity))]
        ///    public class [|UserDTO|]
        ///    {
        ///        public string FirstName { get; set; }
        ///        public string LastName { get; set; }        
        ///    }
        ///    
        ///    public class UserEntity: BaseEntity
        ///    {
        ///        public string FirstName { get; set; }
        ///        publ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _003_MissingPropertiesFromInheritance {
            get {
                return ResourceManager.GetString("_003_MissingPropertiesFromInheritance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using SmartAnalyzers.CSharpExtensions.Annotations;
        ///
        ///namespace CSharpExtensions.Analyzers.Test.RequiredPropertiesInitialization.TestCaseData
        ///{
        ///
        ///    [TwinType(typeof(UserEntity))]
        ///    public class UserDTO
        ///    {
        ///        public int Id { get; set; }
        ///        public int Version { get; set; }
        ///        public string FirstName { get; set; }
        ///        public string LastName { get; set; }        
        ///    }
        ///    
        ///    public class UserEntity: Bas [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _004_NoMissingProperties {
            get {
                return ResourceManager.GetString("_004_NoMissingProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using SmartAnalyzers.CSharpExtensions.Annotations;
        ///
        ///namespace CSharpExtensions.Analyzers.Test.RequiredPropertiesInitialization.TestCaseData
        ///{
        ///
        ///    [TwinType(typeof(UserEntity))]
        ///    public class [|UserDTO|]
        ///    {
        ///        public string FirstName { get; set; }   
        ///    }
        ///    
        ///    public class UserEntity: BaseEntity
        ///    {
        ///        public string FirstName { get; set; }
        ///        public string LastName { get; set; }
        ///        public in [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _005_MissingMembersForFIx {
            get {
                return ResourceManager.GetString("_005_MissingMembersForFIx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using SmartAnalyzers.CSharpExtensions.Annotations;
        ///
        ///namespace CSharpExtensions.Analyzers.Test.RequiredPropertiesInitialization.TestCaseData
        ///{
        ///
        ///    [TwinType(typeof(UserEntity))]
        ///    public class UserDTO
        ///    {
        ///        public string FirstName { get; set; }
        ///        int Age { get; set; }
        ///        string FullName { get; set; }
        ///        int Id { get; set; }
        ///        string LastName { get; set; }
        ///        int Version { get; set; }
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _005_MissingMembersForFIx_FIXED {
            get {
                return ResourceManager.GetString("_005_MissingMembersForFIx_FIXED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using SmartAnalyzers.CSharpExtensions.Annotations;
        ///
        ///namespace CSharpExtensions.Analyzers.Test.RequiredPropertiesInitialization.TestCaseData
        ///{
        ///
        ///    [TwinType(typeof(UserEntity), NamePrefix = &quot;MainAddress&quot;)]
        ///    public class [|UserDTO|]
        ///    {
        ///        public string FirstName { get; set; }
        ///        public string LastName { get; set; }
        ///        public string MainAddressFlatNo { get; set; }
        ///        public string MainAddressBuildingNo { [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _006_PropertiesWithPrefix {
            get {
                return ResourceManager.GetString("_006_PropertiesWithPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using SmartAnalyzers.CSharpExtensions.Annotations;
        ///
        ///namespace CSharpExtensions.Analyzers.Test.RequiredPropertiesInitialization.TestCaseData
        ///{
        ///
        ///    [TwinType(typeof(UserEntity), NamePrefix = &quot;MainAddress&quot;)]
        ///    public class [|UserDTO|]
        ///    {
        ///        public string FirstName { get; set; }
        ///        public string LastName { get; set; }       
        ///    }
        ///    
        ///    public class AddressEntity
        ///    {
        ///        public string FlatNo { get; set;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _007_PropertiesWithPrefixForFix {
            get {
                return ResourceManager.GetString("_007_PropertiesWithPrefixForFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using SmartAnalyzers.CSharpExtensions.Annotations;
        ///
        ///namespace CSharpExtensions.Analyzers.Test.RequiredPropertiesInitialization.TestCaseData
        ///{
        ///
        ///    [TwinType(typeof(UserEntity), NamePrefix = &quot;MainAddress&quot;)]
        ///    public class UserDTO
        ///    {
        ///        public string FirstName { get; set; }
        ///        public string LastName { get; set; }       
        ///    }
        ///    
        ///    public class AddressEntity
        ///    {
        ///        public string FlatNo { get; set; }
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _007_PropertiesWithPrefixForFix_FIXED {
            get {
                return ResourceManager.GetString("_007_PropertiesWithPrefixForFix_FIXED", resourceCulture);
            }
        }
    }
}
