//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharpExtensions.Analyzers.Test.ConvertConstructorToInitBlock {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CompleteInitializationBlockCodeFixTestsCases {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CompleteInitializationBlockCodeFixTestsCases() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSharpExtensions.Analyzers.Test.ConvertConstructorToInitBlock.CompleteInitializat" +
                            "ionBlockCodeFixTestsCases", typeof(CompleteInitializationBlockCodeFixTestsCases).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using SmartAnalyzers.CSharpExtensions.Annotations;
        ///
        ///namespace SimpleTest
        ///{
        ///    class Program
        ///    {
        ///        static void Main(string[] args)
        ///        {
        ///            var x = new User[|(&quot;Cezary&quot;,&quot;Piątek&quot;)|];
        ///            Console.WriteLine(&quot;Hello World!&quot;);
        ///        }
        ///    }
        ///
        ///
        ///    [InitRequired]
        ///    class User
        ///    {
        ///        public string FirstName { get; set; }
        ///        public string LastName { get; set; }
        ///
        ///        public User(string firstName, string lastName)
        ///        {
        ///            [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _001_ConstructorToInitBlock {
            get {
                return ResourceManager.GetString("_001_ConstructorToInitBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using SmartAnalyzers.CSharpExtensions.Annotations;
        ///
        ///namespace SimpleTest
        ///{
        ///    class Program
        ///    {
        ///        static void Main(string[] args)
        ///        {
        ///            var x = new User
        ///            {
        ///                FirstName = &quot;FirstName&quot;,
        ///                LastName = &quot;LastName&quot;
        ///            };
        ///            Console.WriteLine(&quot;Hello World!&quot;);
        ///        }
        ///    }
        ///
        ///
        ///    [InitRequired]
        ///    class User
        ///    {
        ///        public string FirstName { get; set; }
        ///        public string LastName { get;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _001_ConstructorToInitBlock_FIXED {
            get {
                return ResourceManager.GetString("_001_ConstructorToInitBlock_FIXED", resourceCulture);
            }
        }
    }
}
