//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharpExtensions.Analyzers.Test.RequiredPropertiesInitialization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RequiredPropertiesInitializationTestCases {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RequiredPropertiesInitializationTestCases() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSharpExtensions.Analyzers.Test.RequiredPropertiesInitialization.RequiredProperti" +
                            "esInitializationTestCases", typeof(RequiredPropertiesInitializationTestCases).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using SmartAnalyzers.CSharpExtensions.Annotations;
        ///
        ///namespace CSharpExtensions.Analyzers.Test.RequiredPropertiesInitialization.TestCaseData
        ///{
        ///    class Test
        ///    {
        ///        public void DoSomething()
        ///        {
        ///            var user = [|new UserDTO|]()
        ///            {
        ///                FirstName = &quot;John&quot;,
        ///                LastName = &quot;Doe&quot;
        ///            };
        ///        }
        ///    }
        ///
        ///    [InitRequired]
        ///    public class UserDTO
        ///    {
        ///        pu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _001_MissingPropertiesFullInitRequiredAttribute {
            get {
                return ResourceManager.GetString("_001_MissingPropertiesFullInitRequiredAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using SmartAnalyzers.CSharpExtensions.Annotations;
        ///
        ///namespace CSharpExtensions.Analyzers.Test.RequiredPropertiesInitialization.TestCaseData
        ///{
        ///    class Test
        ///    {
        ///        public void DoSomething()
        ///        {
        ///            var user = [|new UserDTO|]()
        ///            {
        ///                FirstName = &quot;John&quot;,
        ///                LastName = &quot;Doe&quot;,
        ///                Age = 20
        ///            };
        ///        }
        ///    }
        ///
        ///    [InitRequired]
        ///    public class [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _002_MissingPropertiesFullInitRequiredAttributeInheritedy {
            get {
                return ResourceManager.GetString("_002_MissingPropertiesFullInitRequiredAttributeInheritedy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using SmartAnalyzers.CSharpExtensions.Annotations;
        ///
        ///namespace CSharpExtensions.Analyzers.Test.RequiredPropertiesInitialization.TestCaseData
        ///{
        ///    class Test
        ///    {
        ///        public void DoSomething()
        ///        {
        ///            var user = [|new UserDTO|]();
        ///        }
        ///    }
        ///
        ///    [InitRequired]
        ///    public class UserDTO
        ///    {
        ///        public string FirstName { get; set; }
        ///        public string LastName { get; set; }
        ///        public int [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _003_MissingPropertiesFullInitRequiredAttributeNoInitBlock {
            get {
                return ResourceManager.GetString("_003_MissingPropertiesFullInitRequiredAttributeNoInitBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using SmartAnalyzers.CSharpExtensions.Annotations;
        ///
        ///namespace CSharpExtensions.Analyzers.Test.RequiredPropertiesInitialization.TestCaseData
        ///{
        ///    class Test
        ///    {
        ///        public void DoSomething()
        ///        {
        ///            var user = /*FullInitRequired*/ [|new UserDTO|]()
        ///            {
        ///                FirstName = &quot;John&quot;,
        ///                LastName = &quot;Doe&quot;
        ///            };
        ///        }
        ///    }
        ///
        ///    public class UserDTO
        ///    {
        ///        p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _004_MissingPropertiesFullInitRequiredComment {
            get {
                return ResourceManager.GetString("_004_MissingPropertiesFullInitRequiredComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using SmartAnalyzers.CSharpExtensions.Annotations;
        ///
        ///namespace CSharpExtensions.Analyzers.Test.RequiredPropertiesInitialization.TestCaseData
        ///{
        ///    class Test
        ///    {
        ///        public void DoSomething()
        ///        {
        ///            var user = /*FullInitRequired*/ [|new UserDTO|]();
        ///        }
        ///    }
        ///
        ///    public class UserDTO
        ///    {
        ///        public string FirstName { get; set; }
        ///        public string LastName { get; set; }
        ///        public in [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _005_MissingPropertiesFullInitRequiredCommentNoInitBlock {
            get {
                return ResourceManager.GetString("_005_MissingPropertiesFullInitRequiredCommentNoInitBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using SmartAnalyzers.CSharpExtensions.Annotations;
        ///
        ///namespace CSharpExtensions.Analyzers.Test.RequiredPropertiesInitialization.TestCaseData
        ///{
        ///    class Test
        ///    {
        ///        public void DoSomething()
        ///        {
        ///            var user = /*FullInitRequired:recursive*/ new UserDTO()
        ///            {
        ///                FirstName = &quot;John&quot;,
        ///                LastName = &quot;Doe&quot;,
        ///                Age = 10,
        ///                Address = [|new AddressDTO|] [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _006_MissingPropertiesFullInitRequiredCommentRecursive {
            get {
                return ResourceManager.GetString("_006_MissingPropertiesFullInitRequiredCommentRecursive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using SmartAnalyzers.CSharpExtensions.Annotations;
        ///
        ///namespace CSharpExtensions.Analyzers.Test.RequiredPropertiesInitialization.TestCaseData
        ///{
        ///    class Test
        ///    {
        ///        public void DoSomething()
        ///        {
        ///            var user = [|new UserDTO|]()
        ///            {
        ///                FirstName = &quot;John&quot;,
        ///                LastName = &quot;Doe&quot;
        ///            };
        ///        }
        ///    }
        ///
        ///    public class UserDTO
        ///    {
        ///        public string FirstNam [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _007_MissingPropertiesMarkedWithInitRequiredAttribute {
            get {
                return ResourceManager.GetString("_007_MissingPropertiesMarkedWithInitRequiredAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using SmartAnalyzers.CSharpExtensions.Annotations;
        ///
        ///namespace CSharpExtensions.Analyzers.Test.RequiredPropertiesInitialization.TestCaseData
        ///{
        ///    class Test
        ///    {
        ///        public void DoSomething()
        ///        {
        ///            var user = new UserDTO()
        ///            {
        ///                FirstName = &quot;John&quot;,
        ///                LastName = &quot;Doe&quot;,
        ///                Age = 10
        ///            };
        ///        }
        ///    }
        ///
        ///    [InitRequired]
        ///    public class Use [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _008_AllPropertiesAssigned {
            get {
                return ResourceManager.GetString("_008_AllPropertiesAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using SmartAnalyzers.CSharpExtensions.Annotations;
        ///
        ///namespace CSharpExtensions.Analyzers.Test.RequiredPropertiesInitialization.TestCaseData
        ///{
        ///    class Test
        ///    {
        ///        public void DoSomething()
        ///        {
        ///            var user = new UserDTO()
        ///            {
        ///                FirstName = &quot;John&quot;,
        ///                LastName = &quot;Doe&quot;,
        ///                Age = 20
        ///            };
        ///        }
        ///    }
        ///
        ///    [InitRequired]
        ///    public class Use [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _009_DoNotReportMissingPropertiesImplementedExplicitly {
            get {
                return ResourceManager.GetString("_009_DoNotReportMissingPropertiesImplementedExplicitly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using SmartAnalyzers.CSharpExtensions.Annotations;
        ///
        ///namespace CSharpExtensions.Analyzers.Test.RequiredPropertiesInitialization.TestCaseData
        ///{
        ///    class Test
        ///    {
        ///        public void DoSomething()
        ///        {
        ///            var user = /*FullInitRequired:recursive*/ new UserDTO()
        ///            {
        ///                FirstName = &quot;John&quot;,
        ///                LastName = &quot;Doe&quot;,
        ///                Address = [|
        ///                {
        ///                    Ci [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _010_MissingPropertiesFullInitRequiredCommentRecursiveWhenNoNewKeyword {
            get {
                return ResourceManager.GetString("_010_MissingPropertiesFullInitRequiredCommentRecursiveWhenNoNewKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using SmartAnalyzers.CSharpExtensions.Annotations;
        ///
        ///namespace CSharpExtensions.Analyzers.Test.RequiredPropertiesInitialization.TestCaseData
        ///{
        ///    class Test
        ///    {
        ///        public void DoSomething()
        ///        {
        ///            var user = new UserDTO()
        ///            {
        ///                FirstName = &quot;John&quot;,
        ///                LastName = &quot;Doe&quot;
        ///            };
        ///        }
        ///    }
        ///
        ///    [InitRequired]
        ///    public class UserDTO
        ///    {
        ///        public [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _011_MissingNotAccessibleProperties {
            get {
                return ResourceManager.GetString("_011_MissingNotAccessibleProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using SmartAnalyzers.CSharpExtensions.Annotations;
        ///
        ///namespace CSharpExtensions.Analyzers.Test.RequiredPropertiesInitialization.TestCaseData
        ///{
        ///    class Test
        ///    {
        ///        public void DoSomething()
        ///        {
        ///            var user = [|new UserDTO|]()
        ///            {
        ///                FirstName = &quot;John&quot;,
        ///                LastName = &quot;Doe&quot;
        ///            };
        ///        }
        ///    }
        ///
        ///    [InitRequired]
        ///    public class UserDTO
        ///    {
        ///        pu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _012_MissingFieldsFullInitRequiredAttribute {
            get {
                return ResourceManager.GetString("_012_MissingFieldsFullInitRequiredAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using SmartAnalyzers.CSharpExtensions.Annotations;
        ///
        ///namespace CSharpExtensions.Analyzers.Test.RequiredPropertiesInitialization.TestCaseData
        ///{
        ///    class Test
        ///    {
        ///        public void DoSomething()
        ///        {
        ///            var user = new UserDTO()
        ///            {
        ///                FirstName = &quot;John&quot;,
        ///                LastName = &quot;Doe&quot;
        ///            };
        ///        }
        ///    }
        ///
        ///    [InitRequired]
        ///    public class UserDTO : IBaseDTO
        ///    {
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _013_DoNotReportMissingPropertiesForInitOnlyOptional {
            get {
                return ResourceManager.GetString("_013_DoNotReportMissingPropertiesForInitOnlyOptional", resourceCulture);
            }
        }
    }
}
